@StudyASS_HostAddress = http://localhost:5136

GET {{StudyASS_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{StudyASS_HostAddress}}/RegisterStudent/
Content-Type: application/json

{
    "studentEmail": "atdenton@lancashire.ac.uk",
    "modules": ["CO3404", "CO2401"]
}

###

GET {{StudyASS_HostAddress}}/students/
Accept: application/json

GET {{StudyASS_HostAddress}}/sessions/
Accept: application/json

GET {{StudyASS_HostAddress}}/registrations/
Accept: application/json

POST {{StudyASS_HostAddress}}/arrange/
Accept: applicatoin/json

###
